### ISSUE TITLE
Korrektur README

### ISSUE THREAD

**Issue by Sabine-Schoenau** [rdmorganiser/terms#1]
Hallo Jochen Klar,

ich habe mir  terms lokal auf einer VM auf meinem Computer installiert und dabei ein, zwei Kleinigkeiten in der README-Datei festgestellt, die mich verwirrt hatten.
Bei srv haben Sie einen Schreibfehler gemacht (es sollte src heißen). 
Die Schritt für Schritt-Anleitung empfand ich teilweise auch etwas schwer nachzuvollziehen. Ich schicke Ihnen mal in einer separaten Datei deine README-Datei, die ich ein klein wenig umgestellt habe.
Ich finde es so etwas einfacher zu verstehen, aber das müssen Sie letztlich entscheiden.

Liebe Grüße,
Sabine Schönau
[Änderung-README.docx](https://github.com/rdmorganiser/terms/files/6768672/Anderung-README.docx)

**Comment by jochenklar** [comment]
Hallo @Sabine-Schoenau , danke! Ich habe das README entsprechend umgebaut.
